/**
 * PersistencePorts —— 持久化层扩展 Port
 *
 * 把"快照存储"与"时间线存储"从 Service 中抽出，
 * 取代 SnapshotService 内部直接 localStorage 的反模式。
 *
 * 设计要点：
 * - 仓储接口纯异步（与现有 IStoryRepository 风格一致）
 * - 实现可选择 IndexedDB（Dexie）或 localStorage（小型数据）
 * - Service 层不再依赖具体实现，可注入 fake
 */

import type { Timeline } from './PostProcessPorts';
export type { Timeline } from './PostProcessPorts';

// ==========================================
// 空间快照实体（由 SnapshotService 定义，此处只引用类型）
// ==========================================

export interface SpaceSnapshot {
  id: string;
  spaceId: string;
  name: string;
  description?: string;
  createdAt: number;
  autoGenerated?: boolean;
  note?: string;
}

// ==========================================
// 快照仓储
// ==========================================

/**
 * 空间快照仓储端口。
 *
 * 实现示例：
 * - SnapshotRepositoryAdapter（Dexie 推荐，跨刷新可靠）
 * - LocalStorageSnapshotRepository（小型数据，调试用）
 * - InMemorySnapshotRepository（测试用）
 *
 * 错误约定：
 * - 仓储不存在时返回 null
 * - 保存失败抛出原始错误（不静默）
 */
export interface ISnapshotRepository {
  save(snapshot: SpaceSnapshot): Promise<void>;
  findById(spaceId: string, snapshotId: string): Promise<SpaceSnapshot | null>;
  findBySpaceId(spaceId: string): Promise<SpaceSnapshot[]>;
  delete(spaceId: string, snapshotId: string): Promise<void>;
  rename(spaceId: string, snapshotId: string, newName: string): Promise<void>;
  /** 触发清理：超过 limit 的旧快照自动删除；返回被删除的数量 */
  trim(spaceId: string, limit: number): Promise<number>;
}

// ==========================================
// 时间线仓储
// ==========================================

/**
 * 时间线仓储端口。
 * Timeline 数据模型已在 PostProcessPorts.ts 中定义，
 * 此 Port 用于持久化用户编排好的剪辑时间线。
 *
 * 使用场景：
 * - 用户在 TimelineEditor 中调整 clip 位置后保存
 * - 切换空间后通过 findByStoryId 恢复
 */
export interface ITimelineRepository {
  save(timeline: Timeline): Promise<void>;
  findById(id: string): Promise<Timeline | null>;
  findByStoryId(storyId: string): Promise<Timeline[]>;
  delete(id: string): Promise<void>;
}
