/**
 * SnapshotService —— 空间快照服务
 *
 * 职责：编排快照创建/查询/恢复的业务流程，**不直接访问 localStorage**。
 * 持久化通过 ISnapshotRepository 抽象完成。
 *
 * v2.0 重构：
 * - 删除内联 localStorage / Map 存储
 * - 改用 ISnapshotRepository
 * - 可选注入 ILoggerPort / IEventBus 用于日志和事件
 */

import { v4 as uuidv4 } from 'uuid';
import type { IStorySpaceRepository } from '../ports/OutboundPorts';
import type { ISnapshotRepository, SpaceSnapshot } from '../ports/PersistencePorts';
import type { ILoggerPort } from '../ports/CrossCuttingPorts';
import type { IEventBus } from '../ports/CrossCuttingPorts';

// 重新导出，保持外部引用兼容
export type { SpaceSnapshot };

export class SnapshotService {
  private spaceRepo: IStorySpaceRepository;
  private snapshotRepo: ISnapshotRepository;
  private logger: ILoggerPort | undefined;
  private eventBus: IEventBus | undefined;
  private maxPerSpace: number;

  constructor(
    spaceRepo: IStorySpaceRepository,
    snapshotRepo: ISnapshotRepository,
    options?: {
      logger?: ILoggerPort;
      eventBus?: IEventBus;
      maxPerSpace?: number;
    }
  ) {
    this.spaceRepo = spaceRepo;
    this.snapshotRepo = snapshotRepo;
    this.logger = options?.logger;
    this.eventBus = options?.eventBus;
    this.maxPerSpace = options?.maxPerSpace ?? 50;
  }

  /**
   * 创建手动快照
   */
  async createSnapshot(spaceId: string, note?: string): Promise<SpaceSnapshot> {
    const space = await this.spaceRepo.findById(spaceId);
    if (!space) throw new Error('Space not found');

    const snapshot: SpaceSnapshot = {
      id: uuidv4(),
      spaceId,
      name: `快照 ${new Date().toLocaleString()}`,
      description: note || '',
      createdAt: Date.now(),
      autoGenerated: false,
      note,
    };

    await this.snapshotRepo.save(snapshot);
    await this.snapshotRepo.trim(spaceId, this.maxPerSpace);
    this.eventBus?.emit('space.snapshot.created', { type: 'space.snapshot.created' as const, snapshotId: snapshot.id, spaceId });
    this.logger?.info('snapshot created', { service: 'SnapshotService', method: 'createSnapshot', spaceId, snapshotId: snapshot.id });
    return snapshot;
  }

  /**
   * 自动快照（删除/重置前的安全网）
   */
  async autoSnapshot(spaceId: string, operation: string): Promise<SpaceSnapshot> {
    return this.createSnapshot(spaceId, `自动快照 (${operation})`);
  }

  /**
   * 获取某空间全部快照（按时间倒序）
   */
  async getSnapshots(spaceId: string): Promise<SpaceSnapshot[]> {
    return this.snapshotRepo.findBySpaceId(spaceId);
  }

  /**
   * 获取单个快照
   */
  async getSnapshot(spaceId: string, snapshotId: string): Promise<SpaceSnapshot | null> {
    return this.snapshotRepo.findById(spaceId, snapshotId);
  }

  /**
   * 删除快照
   */
  async deleteSnapshot(spaceId: string, snapshotId: string): Promise<void> {
    await this.snapshotRepo.delete(spaceId, snapshotId);
    this.logger?.info('snapshot deleted', { service: 'SnapshotService', method: 'deleteSnapshot', spaceId, snapshotId });
  }

  /**
   * 重命名快照
   */
  async renameSnapshot(spaceId: string, snapshotId: string, newName: string): Promise<void> {
    await this.snapshotRepo.rename(spaceId, snapshotId, newName);
  }
}
