import { v4 as uuidv4 } from 'uuid';
import type { IStorySpaceRepository, ICharacterRepository, IBackgroundRepository, IStoryRepository, IVideoTaskRepository, IStorySegmentRepository } from '../ports/OutboundPorts';

export interface SpaceSnapshot {
  id: string;
  spaceId: string;
  name: string;
  description?: string;
  createdAt: number;
  autoGenerated?: boolean;
  note?: string;
}

export class SnapshotService {
  constructor(
    private spaceRepo: IStorySpaceRepository,
    private characterRepo: ICharacterRepository,
    private backgroundRepo: IBackgroundRepository,
    private storyRepo: IStoryRepository,
    private segmentRepo: IStorySegmentRepository,
    private videoTaskRepo: IVideoTaskRepository,
    private snapshots: Map<string, SpaceSnapshot[]>
  ) {}

  /**
   * Create a manual snapshot of the current space state
   */
  async createSnapshot(spaceId: string, note?: string): Promise<SpaceSnapshot> {
    const space = await this.spaceRepo.findById(spaceId);
    if (!space) throw new Error('Space not found');

    const snapshot: SpaceSnapshot = {
      id: uuidv4(),
      spaceId,
      name: `快照 ${new Date().toLocaleString()}`,
      description: note || '',
      createdAt: Date.now(),
      autoGenerated: false,
      note,
    };

    const existing = this.snapshots.get(spaceId) ?? [];
    this.snapshots.set(spaceId, [snapshot, ...existing].slice(0, 50));
    this.saveSnapshots(spaceId);

    return snapshot;
  }

  /**
   * Create an auto-snapshot before destructive operations (delete/reset)
   */
  async autoSnapshot(spaceId: string, operation: string): Promise<SpaceSnapshot> {
    return this.createSnapshot(spaceId, `自动快照 (${operation})`);
  }

  /**
   * Get all snapshots for a space
   */
  getSnapshots(spaceId: string): SpaceSnapshot[] {
    return this.snapshots.get(spaceId) ?? [];
  }

  /**
   * Get a specific snapshot
   */
  getSnapshot(spaceId: string, snapshotId: string): SpaceSnapshot | null {
    const snapshots = this.snapshots.get(spaceId) ?? [];
    return snapshots.find(s => s.id === snapshotId) ?? null;
  }

  /**
   * Delete a snapshot
   */
  deleteSnapshot(spaceId: string, snapshotId: string): void {
    const existing = this.snapshots.get(spaceId) ?? [];
    this.snapshots.set(spaceId, existing.filter(s => s.id !== snapshotId));
    this.saveSnapshots(spaceId);
  }

  /**
   * Rename a snapshot
   */
  renameSnapshot(spaceId: string, snapshotId: string, newName: string): void {
    const existing = this.snapshots.get(spaceId) ?? [];
    const updated = existing.map(s => s.id === snapshotId ? { ...s, name: newName } : s);
    this.snapshots.set(spaceId, updated);
    this.saveSnapshots(spaceId);
  }

  private saveSnapshots(spaceId: string): void {
    try {
      const key = `minimax_space_snapshots_${spaceId}`;
      const snapshots = this.snapshots.get(spaceId) ?? [];
      localStorage.setItem(key, JSON.stringify(snapshots));
    } catch {
      // ignore quota errors
    }
  }

  loadSnapshots(spaceId: string): SpaceSnapshot[] {
    try {
      const key = `minimax_space_snapshots_${spaceId}`;
      const raw = localStorage.getItem(key);
      if (!raw) return [];
      const parsed = JSON.parse(raw) as SpaceSnapshot[];
      this.snapshots.set(spaceId, parsed);
      return parsed;
    } catch {
      return [];
    }
  }
}
